DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

DROP DATABASE IF EXISTS edemamDB;
CREATE DATABASE edemamDB;
CREATE TABLE recipes(
id INT NOT NULL AUTO_INCREMENT,
imageUrl VARCHAR(255),
recipeName VARCHAR(255),
healthDietLabels VARCHAR(255),
shareAsLink VARCHAR(255),
PRIMARY KEY (id)
);